module.exports = {
  PORT: process.env.PORT || 3000, // eslint-disable-line no-magic-numbers

  SLACK_APP_CLIENT_ID: process.env.SLACK_APP_CLIENT_ID,
  SLACK_APP_CLIENT_SECRET: process.env.SLACK_APP_CLIENT_SECRET,
  SLACK_APP_VERIFICATION_TOKEN: process.env.SLACK_APP_VERIFICATION_TOKEN,
  SLACK_APP_OAUTH_ACCESS_TOKEN: process.env.SLACK_APP_OAUTH_ACCESS_TOKEN,

  SLACK_APP_IMMEDIATE_MESSAGE_TIMEOUT_LIMIT: process.env.SLACK_APP_IMMEDIATE_MESSAGE_TIMEOUT_LIMIT || 2000
};